version: '3'

services:
  phoenix:
    build:
      context: .
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
      PGHOST: ${PGHOST}
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - .:/app
      - phoenix_mix_deps:/app/deps
      - phoenix_mix_build:/app/_build
      - phoenix_node_modules:/app/assets/node_modules
    stdin_open: true
    tty: true
  
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata:
  phoenix_mix_build:
  phoenix_mix_deps:
  phoenix_node_modules:
